config/routes.rb
SentinelsApi::Application.routes.draw do
  defaults format: :json do
    resources :cards
    resources :heros
    get '/heroes'                => 'heroes#index'
    get '/heroes/:id/activate'   => 'heroes#activate'
    get '/heroes/:id/deactivate' => 'heroes#deactivate'
    get '/heroes/:id'            => 'heroes#show'
    get '/actives'               => 'application#actives'
    get '/cards/:id/activate'    => 'cards#activate'
    get '/cards/:id/deactivate'  => 'cards#deactivate'
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :hero
end

app/models/hero.rb
class Hero < ActiveRecord::Base
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def actives
    @active_heroes = Hero.where(active: true)
    @active_cards = Card.where(active: true)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  def activate
    @card = Card.find(params[:id])
    @card.update(active: true)
    @card.save!
    render :show
  end

  def deactivate
    @card = Card.find(params[:id])
    @card.update(active: false)
    @card.save!
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :hp, :does, :effects, :flavor_text, :kind)
    end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heroes = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
    @hero = Hero.find(params[:id])
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hero }
      else
        format.html { render action: 'new' }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url }
      format.json { head :no_content }
    end
  end

  def activate
    @hero = Hero.find(params[:id])
    @hero.update(active: true)
    @hero.save!
    render :show
  end

  def deactivate
    @hero = Hero.find(params[:id])
    @hero.update(active: false)
    @hero.save!
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :hp, :effects, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hp %><br>
    <%= f.number_field :hp %>
  </div>
  <div class="field">
    <%= f.label :does %><br>
    <%= f.text_field :does %>
  </div>
  <div class="field">
    <%= f.label :effects %><br>
    <%= f.text_field :effects %>
  </div>
  <div class="field">
    <%= f.label :flavor_text %><br>
    <%= f.text_field :flavor_text %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>
      <th>Does</th>
      <th>Effects</th>
      <th>Flavor text</th>
      <th>Kind</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.hp %></td>
        <td><%= card.does %></td>
        <td><%= card.effects %></td>
        <td><%= card.flavor_text %></td>
        <td><%= card.kind %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @card.hp %>
</p>

<p>
  <strong>Does:</strong>
  <%= @card.does %>
</p>

<p>
  <strong>Effects:</strong>
  <%= @card.effects %>
</p>

<p>
  <strong>Flavor text:</strong>
  <%= @card.flavor_text %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @card.kind %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/heroes/_form.html.erb
<%= form_for(@hero) do |f| %>
  <% if @hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% @hero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hp %><br>
    <%= f.number_field :hp %>
  </div>
  <div class="field">
    <%= f.label :effects %><br>
    <%= f.text_field :effects %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heroes/edit.html.erb
<h1>Editing hero</h1>

<%= render 'form' %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heroes/index.html.erb
<h1>Listing heros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>
      <th>Effects</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= hero.hp %></td>
        <td><%= hero.effects %></td>
        <td><%= hero.active %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

app/views/heroes/new.html.erb
<h1>New hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heros_path %>

app/views/heroes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @hero.hp %>
</p>

<p>
  <strong>Effects:</strong>
  <%= @hero.effects %>
</p>

<p>
  <strong>Active:</strong>
  <%= @hero.active %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SentinelsApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>